# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-22 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='message',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wall_app.Messages'),
            preserve_default=False,
        ),
    ]
