# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-21 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0007_auto_20190621_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wall_app.User'),
            preserve_default=False,
        ),
    ]
