# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-21 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0008_comment_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
